patterns:
  image:
    width: 400
    fields:
      - name: title
        type: string
        example: "Iguanodon"
      - name: details
        type: string
        example: "Save a Iguanodon from utter destruction."
      - name: image
        type: image
        example: "Iguanodon.jpg"
      - name: button_text
        type: string
        example: "Rescue a Iguanodon"
